# --------------------------------------
# Hexo Butterfly 主题配置
# 如有疑问请查阅文档：
# 中文文档: https://butterfly.js.org/
# 英文文档: https://butterfly.js.org/en/
# --------------------------------------

# --------------------------------------
# 导航栏设置
# --------------------------------------
nav:
  logo:          # 导航栏LOGO图片路径
  display_title: true  # 是否显示网站标题
  fixed: false   # 是否固定导航栏

menu:           # 导航菜单配置
  # 示例格式：主页: / || fas fa-home

# --------------------------------------
# 代码块设置
# --------------------------------------
code_blocks:
  theme: light  # 代码主题：darker/pale night/light/ocean/false
  macStyle: false  # 显示Mac风格代码栏
  height_limit: false  # 代码块高度限制（单位像素）
  word_wrap: false  # 自动换行
  
  # 工具栏设置
  copy: true     # 显示复制按钮
  language: true # 显示语言标识
  shrink: false  # 代码块折叠：true折叠/false展开/none隐藏按钮
  fullpage: false # 全屏显示

# --------------------------------------
# 社交链接
# 格式：图标: 链接 || 描述 || 颜色
# --------------------------------------
social:
  # 示例：fab fa-github: https://github.com/xxx || Github || '#24292e'

# --------------------------------------
# 图片设置
# --------------------------------------
favicon: /img/favicon.png  # 网站图标

avatar:         # 头像设置
  img: /img/butterfly-icon.png
  effect: false # 头像悬停效果

disable_top_img: false  # 禁用所有顶部图片
default_top_img:       # 默认顶部图片（当页面未设置时显示）
index_img:            # 首页顶部图片
archive_img:          # 归档页顶部图片
tag_img:              # 标签页顶部图片（单个标签页）
tag_per_img:          # 按标签设置顶部图（格式：- 标签名: 图片路径）
category_img:         # 分类页顶部图片（单个分类页）
category_per_img:     # 按分类设置顶部图
footer_img: false     # 页脚背景图片
background:          # 网站背景（颜色或图片URL）

# 封面设置
cover:
  index_enable: true   # 首页封面
  aside_enable: true   # 侧边栏封面
  archives_enable: true # 归档页封面
  default_cover:      # 默认封面图片
    # - xxx.jpg

# 错误图片配置
error_img:
  flink: /img/friend_404.gif  # 失效友链图片
  post_page: /img/404.jpg     # 文章404图片

# 404页面设置
error_404:
  enable: false
  subtitle: '页面未找到'
  background: /img/error-page.png
  # --------------------------------------
# 文章元数据设置
# --------------------------------------
post_meta:
  page:          # 主页显示
    date_type: created   # 日期类型：created/updated/both
    date_format: date    # 日期格式：date/relative
    categories: true     # 显示分类
    tags: false          # 显示标签
    label: true          # 显示图标
    
  post:          # 文章页显示
    position: left       # 位置：left/center
    date_type: both      # 日期类型
    date_format: date    # 日期格式
    categories: true     # 显示分类
    tags: true           # 显示标签
    label: true          # 显示图标

# --------------------------------------
# 首页设置
# --------------------------------------
index_site_info_top:    # 首页顶部图文字位置（如：300px）
index_top_img_height:   # 首页顶部图高度（如：300px）

# 首页副标题设置
subtitle:
  enable: false
  effect: true         # 打字机效果
  typed_option:        # 自定义打字机配置
  source: false        # 第三方语录源（1/2/3）
  sub:                # 自定义副标题

index_layout: 3       # 首页文章布局（1-7种模式）
index_post_content:   # 首页文章摘要
  method: 3           # 1:仅描述 2:优先描述 3:自动摘要
  length: 500         # 摘要长度

# --------------------------------------
# 文章页设置
# --------------------------------------
toc:                 # 目录设置
  post: true         # 文章页启用
  page: false        # 普通页禁用
  number: true       # 显示编号
  expand: false      # 默认展开
  style_simple: false # 简洁模式
  scroll_percent: true # 显示阅读进度

post_copyright:      # 文章版权声明
  enable: true
  decode: false      # 解码特殊符号
  license: CC BY-NC-SA 4.0 # 许可协议
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:              # 打赏功能
  enable: false
  text:              # 打赏提示文字
  QR_code:           # 二维码配置
    # 示例：- img: /img/wechat.jpg
    # --------------------------------------
# 页脚设置
# --------------------------------------
footer:
  owner:
    enable: true    # 显示建站时间
    since: 2019
  custom_text:      # 自定义文本
  copyright: true   # 显示主题版权信息

# --------------------------------------
# 侧边栏设置
# --------------------------------------
aside:
  enable: true
  hide: false       # 默认隐藏
  button: true      # 显示隐藏按钮
  mobile: true      # 移动端显示
  position: right   # 显示位置：left/right
  display:          # 显示模块
    archive: true   # 归档
    tag: true       # 标签
    category: true  # 分类

  card_author:      # 作者卡片
    enable: true
    description:    # 个人描述
    button:
      enable: true
      icon: fab fa-github
      text: 关注我
      link: https://github.com/xxxxxx

  card_announcement: # 公告卡片
    enable: true
    content: 这是我的博客

  card_recent_post:  # 最新文章
    enable: true
    limit: 5         # 显示数量
    sort: date       # 排序方式：date/updated

  card_categories:   # 分类目录
    enable: true
    limit: 8         # 显示数量
    expand: none     # 展开方式：none/true/false

  card_tags:         # 标签云
    enable: true
    limit: 40        # 显示数量
    color: false     # 彩色标签
    orderby: random  # 排序方式：random/name/length

# --------------------------------------
# 右下角功能按钮
# --------------------------------------
rightside_bottom:   # 按钮底部间距（单位像素）

translate:          # 简繁转换
  enable: false
  default: 简
  defaultEncoding: 2

readmode: true      # 阅读模式
rightside_scroll_percent: false # 显示滚动百分比

darkmode:           # 暗黑模式
  enable: true
  button: true      # 切换按钮
  autoChangeMode: false # 自动切换模式
  # --------------------------------------
# 高级功能设置
# --------------------------------------
math:               # 数学公式
  use:              # 启用引擎：mathjax/katex
  per_page: true    # 全局加载
  hide_scrollbar: false

search:             # 搜索功能
  use:              # 选择引擎：algolia_search/local_search/docsearch

share:              # 分享功能
  use: sharejs      # 选择引擎：sharejs/addtoany

comments:           # 评论系统
  use:              # 最多两个系统（如：Disqus,Waline）
  lazyload: false   # 延迟加载

# --------------------------------------
# 统计与分析
# --------------------------------------
busuanzi:           # 不蒜子统计
  site_uv: true     # 访客数
  site_pv: true     # 访问量
  page_pv: true     # 页面访问

google_analytics:   # Google分析
baidu_analytics:    # 百度统计

# --------------------------------------
# 特效与美化
# --------------------------------------
preloader:          # 加载动画
  enable: false
  source: 1         # 类型：1=全屏加载/2=进度条

activate_power_mode: # 打字特效
  enable: false
  colorful: true
  shake: true

canvas_ribbon:      # 背景彩带
  enable: false
  size: 150
  alpha: 0.6

# --------------------------------------
# 性能优化
# --------------------------------------
lazyload:           # 图片懒加载
  enable: false
  field: site       # 应用范围：site/post

pjax:               # 页面无刷新加载
  enable: false
  exclude:          # 排除路径
    # - /music/

# --------------------------------------
# 其他高级设置
# --------------------------------------
CDN:                # CDN配置
  internal_provider: local
  third_party_provider: jsdelivr
